# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftStudy' do
  source 'https://cdn.cocoapods.org'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftStudy
pod 'Moya'
pod 'Kingfisher'
pod 'SnapKit'
pod 'IQKeyboardManagerSwift'

end
