# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'SwiftStudy' do
  source 'https://cdn.cocoapods.org'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftStudy
pod 'Moya'
pod 'Kingfisher'
pod 'SnapKit'
pod 'IQKeyboardManagerSwift'
pod 'Alamofire'
pod 'RxAlamofire'
pod 'Moya'
pod 'Moya/RxSwift'
pod 'RxSwift'
pod 'RxCocoa'
pod 'RxDataSources'
pod 'AlamofireObjectMapper'
pod 'MJRefresh'


end
